---
title: "Problem set 1-Zhenze Huang"
format: 
  html:
    self-contained: true
editor: visual
execute: 
  warning: false
  message: false
---

## Question 1

Imagine you hypothesize that the probability of voting for the incumbent in a two-candidate race is higher for those who are 30 to 65 years old than for those older than 65.

Using the table of survey results below answer questions 1a, 1b, 1c, and 1d. Please show all of your work.

| Age           | Challenger | Incumbent | TOTAL |
|---------------|------------|-----------|-------|
| 18 to 29      | 210        | 250       | 460   |
| 30 to 65      | 245        | 150       | 395   |
| Older than 65 | 160        | 150       | 310   |
| **TOTAL**     | 615        | 550       | 1165  |

: Voting for the Incumbent and Challenger by Age (cell counts)

### Part A

What is the probability of voting for the incumbent? (1 point)

P (voting for the incumbent)= Total votes for incumbent/total votes: 550/1165= 47.2%

### Part B

What is the probability of being 18-29 or voting for the incumbent? Write the general (i.e. using symbols) formula you used to obtain your answer and show all of your work. (2 points)

$P(A ∪ B)$ = $P(A)$ + $P(B)$ - $P(A ∩ B)$

= P (being 18-29) + P (voting for incumbent) - P (being 18-29 and voting for incumbent)

=（460/1165）+（550/1165）-（250/1165）

= 65.2%

### Part C

In terms of the substantive results (ignore statistical significance), does the evidence support your hypothesis? Explain, using details, how you know (no more than 2 sentences). (5 points)

P (being 30-65 voting for the incumbent): 150 / 395 = 38.0%

P (being older than 65 voting for the incumbent): 150 / 310 = 48.4%

P (being 30-65 voting for the incumbent) \< P (being older than 65 voting for the incumbent)

No, the evidence does not support the hypothesis as the probability of voting for the incumbent in a two-candidate race is higher for those older than 65 than those who are 30 and 65.

### Part D

Imagine that the values in the **Total** column for each age group in *Table 1* remained the same, but the percentage voting for the incumbent in each age group was 51% (i.e. 51% of each age group voted for the incumbent). Now imagine that you were going to construct 90% confidence intervals, using the z table, for the percentage voting for the incumbent for each age group (don’t actually do this). List the age groups in order starting with the one that would have the widest confidence interval to the one that would have the narrowest confidence interval, noting any ties. (3 points)

$\text{CI Width} = p ± Z \times \sqrt{\frac{p(1-p)}{n}}$

CI Width(18-29)= $0.51 ± 1.645 \times \sqrt{\frac{0.51(1-0.51)}{460}}$ $≈$ （0.434，0.586）

CI Width(30-65)= $0.51 ± 1.645 \times \sqrt{\frac{0.51(1-0.51)}{395}}$ $≈$ （0.433，0.587）

CI Width(65 and older)= $0.51 ± 1.645 \times \sqrt{\frac{0.51(1-0.51)}{310}}$ $≈$ （0.430，0.590）

Groups from the widest confidence interval to the narrowest confidence interval: voters (65 and older), voters (30-65), voters (18-29).

## Question 2

Provide a political science example of a nominal variable. (1 point)

The candidate's political party affiliation (the Democrats or Republican) is an example of a nominal variable in political science.

## Question 3

What is the OLS estimate of $Y = \beta_0 + \epsilon$? (That is, in terms of $Y$, what does the OLS estimate of $\beta_0$ equal?) (2 points)

In the equation $Y = \beta_0 + \epsilon$ , the term $\beta_0$ represents the intercept of the linear model. In OLS regression, the OLS estimate of $\beta_0$ is denoted as $\hat{\beta}_0$ . The OLS estimate of $\hat{\beta}_0$ is the predicted value of $Y$ when all independent variable are set to 0. Therefore, the OLS estimate in terms of $Y$ is: $\hat{Y}$ = $\hat{\beta}_0$.

In other words, the OLS estimate of $\hat{\beta}_0$​ is equal to the predicted value of $Y$ when all independent variables are zero. This represents the y-intercept in the linear regression model.

## Question 4

Answer the questions below based on the following information and table.

$N = 1,200$ from a random sample of 18 and older Canadians.

**Dependent variable:** Feeling Thermometer Rating of George W. Bush (0 to 100: 0 = very cold, 100 = very warm)

**Independent variables:** age (in years), education (in years), have access to U.S. TV stations (1 = yes, 0 = no), ideology (7 point scale: 1 = very liberal, 7 = very conservative)

| Independent variables | Coefficient | SE  | p-value |
|-----------------------|-------------|-----|---------|
| Constant              | 50          | 20  | 0.0126  |
| Age                   | 0.5         | 1   | 0.6172  |
| Education             | -2          | 0.2 | 0.0000  |
| U.S. TV Access        | -5          | 2   | 0.0126  |
| Ideology              | 6           | 3.2 | 0.0610  |

: Hypothetical Regression Results Predicting George W. Bush Thermometer Ratings

### Part A

Calculate the t-statistic for `Education`. (1 point)

t (Education) = -2/0.2 = -10

### Part B

Interpret the results for the `Education` variable, i.e. BRIEFLY discuss the substantive meaning of the results (1 sentence), substantive significance (no more than 2 sentences), and statistical significance (1 sentence). (5 points)

Substantive significance: 1. For each additional year of education, there is a decrease of 2 units in the willingness to support freedom compared to the reference. 2. The coefficient for education is statistically significant as the p-value is 0.0000.

### Part C

In this context, is the coefficient on the constant term useful on its own? Why or why not (1 sentence) (5 points)

Yes, the coefficient of the constant term is useful as it represents the baseline level of the dependent variable when all independent variables are 0, and it is statistically significant with a p-value of 0.0126.

### Part D

Is the coefficient on `U.S. TV access` statistically significant at the 5% error level? (1 point)

Yes, the coefficient of U.S. TV Access is statistically significant at the 5% level, as the p-value is only 0.0126 (\< 0.05).

### Part E

Is the coefficient on `U.S. TV access` statistically significant at the 1% error level? (1 point)

No, the coefficient of U.S. TV Access is not statistically significant at the 1% level, as the p-value (0.0126) is greater than 1% significance level.

### Part F

Based on the results in *Table 2*, might the negative coefficient on `U.S. TV Access` be the result of more educated people being more likely to have access to U.S. TV? In no more than 1 sentence, explain your answer. (3 points)

Yes, we can use the negative coefficient to interpret that individuals with higher education are more likely to oppose watching American television.
